library(Seurat)
library(cowplot)
library(stringr)

source('preprocess_dataset.R')
source('integrate_datasets.R')

Analysis_5FU <- function(processed_path, analysis_path, results_path) {

  N_samples = 5
  samples = c("FO898/SC", "SB133/SC", "FO892/SC/1", "FO892/SC/2", "FO897/SC")
  umi_cutoff = c(1539, 1319, 1632, 2113, 2012)

  # The UMI cutoffs here are from the automatically computed cutoffs stored 
  # in Transcriptome.mat generated by process_transcriptomes
  
  output_paths <- vector(mode = "list", length = N_samples)
  dataset_list <- vector(mode = "list", length = N_samples)
  
  for (i in 1:N_samples) {
    input_matrix <- paste(processed_path, '5FU', samples[[i]], 'Transcriptome/filtered_feature_bc_matrix.h5', sep='/')
    output_paths[[i]] <- paste(analysis_path, '5FU', samples[[i]], 'Transcriptome/Seurat', sep='/')
    dataset_list[[i]] <- preprocess_dataset(input_matrix, '5FU', samples[[i]], umi_cutoff[[i]], output_paths[[i]])
  }
  
  marker_genes = scan("marker_genes.txt", what="", sep="\n")
  combined_path <- paste(analysis_path, '5FU/V3Combined/Transcriptome/Seurat', sep='/')
  
  integrated <- integrate_datasets(dataset_list, marker_genes, combined_path)
  
  for (i in 1:N_samples) {
    write.table(integrated@reductions$umap@cell.embeddings[integrated$sample==samples[[i]],], paste(output_paths[[i]], 'UMAPCoordinates.csv', sep='/'), col.names = F, sep=",")
    write.table(integrated$integrated_snn_res.1.5[integrated$sample==samples[[i]]], paste(output_paths[[i]], 'LouvainClusters.csv', sep='/'), col.names = F, sep=",")
  }
  
  DefaultAssay(integrated) <- "RNA"
  dp = DotPlot(object=integrated, features = marker_genes) + RotatedAxis()
  
  dir.create(paste(results_path, '5FU/Seurat', sep='/'), showWarnings = FALSE, recursive = TRUE)
  write.table(dp$data, paste(results_path, '5FU/Seurat/DotPlot.csv', sep='/'), col.names = F, sep=",")
  
}
