library(Seurat)
library(cowplot)
library(stringr)

source('preprocess_dataset.R')
source('integrate_datasets.R')

Analysis_EB <- function(processed_path, analysis_path, results_path) {

  N_samples = 4
  samples = c("LF", "RF", "LH", "RH")
  umi_cutoff = c(2383, 2697, 2122, 1095)

  # The UMI cutoffs here are from the automatically computed cutoffs stored 
  # in Transcriptome.mat generated by process_transcriptomes
  
  output_paths <- vector(mode = "list", length = N_samples)
  dataset_list <- vector(mode = "list", length = N_samples)
  
  for (i in 1:N_samples) {
    input_matrix <- paste(processed_path, 'EB/FO864/SC', samples[[i]], 'Transcriptome/filtered_feature_bc_matrix.h5', sep='/')
    output_paths[[i]] <- paste(analysis_path, 'EB/FO864/SC', samples[[i]], 'Transcriptome/Seurat', sep='/')
    dataset_list[[i]] <- preprocess_dataset(input_matrix, "EB", samples[[i]], umi_cutoff[[i]], output_paths[[i]])
  }
  
  marker_genes = scan("marker_genes.txt", what="", sep="\n")
  combined_path <- paste(analysis_path, 'EB/FO864/SC/Combined/Transcriptome/Seurat', sep='/')
  
  integrated <- integrate_datasets(dataset_list, marker_genes, combined_path);
  
  for (i in 1:N_samples) {
    write.table(integrated@reductions$umap@cell.embeddings[integrated$sample==samples[[i]],], paste(output_paths[[i]], 'UMAPCoordinates.csv', sep='/'), col.names = F, sep=",")
    write.table(integrated$integrated_snn_res.1.5[integrated$sample==samples[[i]]], paste(output_paths[[i]], 'LouvainClusters.csv', sep='/'), col.names = F, sep=",")
  }
  
  DefaultAssay(integrated) <- "RNA"
  dp = DotPlot(object=integrated, features = marker_genes) + RotatedAxis()
  
  dir.create(paste(results_path, 'EB/Seurat', sep='/'), showWarnings = FALSE, recursive = TRUE)
  write.table(dp$data, paste(results_path, 'EB/Seurat/DotPlot.csv', sep='/'), col.names = F, sep=",")
  
}
